### ISSUE TITLE
About the Distance Transform Pooling Layer

### ISSUE THREAD

**Issue by bearpaw** [rbgirshick/DeepPyramid#4]
Hi Ross,

This code only computes the feature pyramid. Would you please provide the Distance transform pooling layer (I guess you implemented a new Caffe layer) as a reference? Thank you.

**Comment by rbgirshick** [comment]
@bearpaw, code for the CVPR paper is now online here: https://github.com/rbgirshick/dp-dpm. Note that this follows what was described in the paper, i.e., Latent SVM training of a DPM on top of pre-computed deep features.
