### ISSUE TITLE
run 'demo_deep_pyramid.m', get  error using caffel.....,

### ISSUE THREAD

**Issue by zhangli1992** [rbgirshick/DeepPyramid#7]
Error using caffe
Expected 3 arguments, got 2
Error in init_cnn_model (line 60)
      caffe('init', cnn.definition_file, cnn.binary_file);
Error in demo_deep_pyramid (line 43)
cnn = init_cnn_model('use_gpu', USE_GPU, 'use_caffe', USE_CAFFE);

 However I could run dp-dpm succeed, with matlab2015,caffe-0.999,Tesla K40

**Comment by kashefy** [comment]
It seems the usage of Caffe in [init_cnn_model.m](https://github.com/rbgirshick/DeepPyramid/blob/master/init_cnn_model.m) is outdated and was written before the caffe.Net class was introduced to Caffe's Matlab interface.
[Here](https://github.com/BVLC/caffe/blob/master/matlab/demo/classification_demo.m#L84) is a more up to date example on instantiating a caffe network instance.
Example:
`net = caffe.Net(cnn.definition_file, cnn.binary_file, 'test');`

Further changes may still be needed that update how dp-dpm uses this `net` object.

**Comment by zhangli1992** [comment]
@kashefy Thanks, I have solved this problem, this code is fit to caffe-1.0,the caffe_init,. include two arguments
